### ISSUE TITLE
[BUG] My settings are lost after every update

### ISSUE THREAD

**Issue by trlef19** [unchihugo/FluentFlyout#43]
**Describe the bug**
Every time there is an update to the app, i have to configure my settings again cause they have been reset to default

**Expected behavior**
The changes i make, retain after an update

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version [all]

**Comment by unchihugo** [comment]
Hi! I've mentioned this in [v1.3.4 changelog](https://github.com/unchihugo/FluentFlyout/releases/tag/v1.3.4), basically **from now onwards settings will no longer reset on every update** :)

Unfortunately, like I mentioned in the update notes, the settings will reset one last time upon updating before converting to the new settings system, there's nothing I can do to fix that.

It used to reset because I used Microsoft's built in settings editor, which stored settings in a weird way. I have now designed my own system and should store updates in a safe way that will not reset after each update.

Feel free to re-open this issue if you still encounter issues. Thank you for using FluentFlyout!

**Comment by trlef19** [comment]
oh okay, sorry i didnt look deeper
